SET(vtkzlib_LIB_DEPENDS "")
SET(vtkjpeg_LIB_DEPENDS "")
SET(vtkpng_LIB_DEPENDS "vtkzlib;")
SET(vtktiff_LIB_DEPENDS "vtkzlib;vtkjpeg;")
SET(vtkexpat_LIB_DEPENDS "")
SET(vtkDICOMParser_LIB_DEPENDS "")
SET(vtkfreetype_LIB_DEPENDS "-framework AppKit;")
SET(vtkftgl_LIB_DEPENDS "-framework AGL;-framework OpenGL;vtkfreetype;")
SET(vtkCommon_LIB_DEPENDS "-framework AppKit;-lpthread;-lm;")
SET(vtkCommonTCL_LIB_DEPENDS "vtkCommon;/opt/rappture/lib/libtcl8.4.dylib;")
SET(vtkFiltering_LIB_DEPENDS "vtkCommon;")
SET(vtkFilteringTCL_LIB_DEPENDS "vtkFiltering;vtkCommonTCL;")
SET(vtkImaging_LIB_DEPENDS "vtkFiltering;")
SET(vtkImagingTCL_LIB_DEPENDS "vtkImaging;vtkFilteringTCL;")
SET(vtkGraphics_LIB_DEPENDS "vtkFiltering;")
SET(vtkGraphicsTCL_LIB_DEPENDS "vtkGraphics;vtkFilteringTCL;")
SET(vtkIO_LIB_DEPENDS "vtkFiltering;vtkDICOMParser;vtkpng;vtkzlib;vtkjpeg;vtktiff;vtkexpat;")
SET(vtkIOTCL_LIB_DEPENDS "vtkIO;vtkFilteringTCL;")
SET(vtkRendering_LIB_DEPENDS "vtkGraphics;vtkImaging;vtkIO;vtkftgl;vtkfreetype;-framework AGL;-framework OpenGL;-lXt;-lSM;-lICE;/usr/X11R6/lib/libX11.a;/usr/X11R6/lib/libXext.a;")
SET(vtkRenderingTCL_LIB_DEPENDS "vtkRendering;vtkGraphicsTCL;vtkImagingTCL;/opt/rappture/lib/libtcl8.4.dylib;/opt/rappture/lib/libtk8.4.dylib;")
SET(vtkHybrid_LIB_DEPENDS "vtkRendering;vtkIO;")
SET(vtkHybridTCL_LIB_DEPENDS "vtkHybrid;vtkRenderingTCL;vtkIOTCL;")
SET(vtkParallel_LIB_DEPENDS "vtkRendering;vtkIO;")
SET(vtkParallelTCL_LIB_DEPENDS "vtkParallel;vtkRenderingTCL;vtkIOTCL;")
